// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJj7LPRPrGJGudGLObAP7Da_BP2bYoWA',
    appId: '1:478781953349:web:2d72f70bf4c9ddd005da2c',
    messagingSenderId: '478781953349',
    projectId: 'islamic-learning-project',
    authDomain: 'islamic-learning-project.firebaseapp.com',
    storageBucket: 'islamic-learning-project.firebasestorage.app',
    measurementId: 'G-6H6BS1JKD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp0eR6q9UFt6VJlG3dK40fMbXjvX-tSyQ',
    appId: '1:478781953349:android:524f25a32d422b5e05da2c',
    messagingSenderId: '478781953349',
    projectId: 'islamic-learning-project',
    storageBucket: 'islamic-learning-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADTz4Ei8CjzYHrawdbMg-1-fSDVpcM4XI',
    appId: '1:478781953349:ios:67f94643032085eb05da2c',
    messagingSenderId: '478781953349',
    projectId: 'islamic-learning-project',
    storageBucket: 'islamic-learning-project.firebasestorage.app',
    iosBundleId: 'com.example.quranteacher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADTz4Ei8CjzYHrawdbMg-1-fSDVpcM4XI',
    appId: '1:478781953349:ios:67f94643032085eb05da2c',
    messagingSenderId: '478781953349',
    projectId: 'islamic-learning-project',
    storageBucket: 'islamic-learning-project.firebasestorage.app',
    iosBundleId: 'com.example.quranteacher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFJj7LPRPrGJGudGLObAP7Da_BP2bYoWA',
    appId: '1:478781953349:web:44598c38b3d0821a05da2c',
    messagingSenderId: '478781953349',
    projectId: 'islamic-learning-project',
    authDomain: 'islamic-learning-project.firebaseapp.com',
    storageBucket: 'islamic-learning-project.firebasestorage.app',
    measurementId: 'G-12DM0Q21XC',
  );
}
